set -sg escape-time 10

set -g history-limit 50000

set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

setw -g mode-keys vi

# Enable OSC 52 clipboard integration
set -g set-clipboard on
set -g allow-passthrough on

set -g mouse on
